// WikiRenderer.swift — turn an AuditReport into human-facing artifacts.
//
// Three markdown files (the deliverables of the pattern) plus a compact console
// summary:
//   CONTEXT-WIKI.md         the consolidated cross-reference graph
//   CONTEXT-SCHEMA.md       the conventions that prevent re-bloat (verbatim from
//                           the report — the consolidator already generated it)
//   RECOMMENDATIONS.md      the ranked cleanups, each destructive one behind an
//                           explicit `[ ]` sign-off checkbox
//
// The renderer is pure string-building over the report; `writeArtifacts` is the
// only side-effecting method and it writes ONLY into a caller-chosen output
// directory — never the source tree. This keeps the "surface, never auto-destroy"
// guarantee visible in the code: rendering can't touch a raw source.

import Foundation

public struct WikiRenderer: Sendable {

    public init() {}

    // MARK: - Console summary

    /// A short, skimmable summary for a terminal / log line. One headline plus
    /// the top few recommendations.
    public func consoleSummary(_ report: AuditReport, topN: Int = 8) -> String {
        var out: [String] = []
        out.append("Context Wiki audit — \(report.root)")
        out.append(String(repeating: "─", count: 56))
        out.append("Sources:        \(report.metrics.totalSources) total, \(report.metrics.proseSources) context/prose (\(report.metrics.totalProseLines) lines)")
        let rawReclaimable = report.metrics.duplicateBlocks.reduce(0) { $0 + $1.reclaimableLines }
        out.append("Duplication:    \(report.metrics.duplicateBlocks.count) block(s), ~\(rawReclaimable) reclaimable lines (raw)")
        if report.metrics.nonContextBytes > 0 {
            out.append("Non-context:    \(Self.humanBytes(report.metrics.nonContextBytes)) in scripts/assets (not loaded as context)")
        }
        out.append("Semantic survey: \(report.usedLLM ? "\(report.surveys.count) file(s)" : "skipped (deterministic-only)")")
        out.append("Top severity:   \(report.topSeverity.rawValue)")
        out.append("")
        let actionable = report.recommendations.filter { $0.kind != .schemaRule }
        out.append("Recommendations (\(actionable.count) actionable, \(report.recommendations.count - actionable.count) schema rules):")
        for (i, rec) in report.recommendations.prefix(topN).enumerated() {
            let gate = rec.requiresSignoff ? " ⚑needs sign-off" : ""
            out.append("  \(i + 1). [\(rec.severity.rawValue)/\(rec.kind.rawValue)] \(rec.title)\(gate)")
        }
        if report.recommendations.count > topN {
            out.append("  … and \(report.recommendations.count - topN) more (see RECOMMENDATIONS.md)")
        }
        return out.joined(separator: "\n")
    }

    // MARK: - Wiki

    public func renderWiki(_ report: AuditReport) -> String {
        var s = "# Context Wiki\n\n"
        s += "> The consolidated, cross-referenced view of this project's AI-context\n"
        s += "> surfaces. Generated by Supervisor from the raw sources (read-only).\n\n"
        s += "Root: `\(report.root)`  \n"
        s += "Generated: \(Self.iso(report.generatedAt))  \n"
        s += "Sources: \(report.metrics.totalSources) (\(report.metrics.proseSources) context/prose)\n\n"

        // Inventory table.
        s += "## Raw sources\n\n"
        s += "| Source | Kind | Lines | Size |\n|---|---|--:|--:|\n"
        for src in report.sources {
            let label = src.skill.map { "\($0)/\((src.path as NSString).lastPathComponent)" } ?? (src.path as NSString).lastPathComponent
            let lines = src.isText ? "\(src.lineCount)" : "—"
            s += "| `\(label)` | \(src.kind.rawValue) | \(lines) | \(Self.humanBytes(src.byteCount)) |\n"
        }
        s += "\n"

        // Cross-reference graph: duplicated topics first.
        let duplicated = report.wiki.filter { $0.isDuplicated }
        s += "## Cross-references\n\n"
        if duplicated.isEmpty {
            s += "_No cross-file duplication detected._\n\n"
        } else {
            s += "Topics that appear in more than one source. The **home** is the\n"
            s += "suggested canonical location; the others should link to it.\n\n"
            for topic in duplicated.prefix(60) {
                s += "- **\(Self.escape(topic.name))**\n"
                if let home = topic.canonicalHome {
                    s += "  - home: `\((home as NSString).lastPathComponent)`\n"
                }
                let others = topic.appearsIn.filter { $0 != topic.canonicalHome }
                if !others.isEmpty {
                    s += "  - also in: " + others.map { "`\(($0 as NSString).lastPathComponent)`" }.joined(separator: ", ") + "\n"
                }
            }
            s += "\n"
        }

        // Surveys (only when the LLM pass ran).
        if report.usedLLM && !report.surveys.isEmpty {
            s += "## Per-source survey\n\n"
            for survey in report.surveys.sorted(by: { $0.bloatScore > $1.bloatScore }) {
                s += "### `\((survey.path as NSString).lastPathComponent)` — bloat \(survey.bloatScore)/5\n"
                if !survey.purpose.isEmpty { s += "\(Self.escape(survey.purpose))\n\n" }
                if !survey.deadWeight.isEmpty {
                    s += "- dead weight: " + survey.deadWeight.prefix(5).map(Self.escape).joined(separator: "; ") + "\n"
                }
                if !survey.overlapsNotes.isEmpty {
                    s += "- overlaps: " + survey.overlapsNotes.prefix(4).map(Self.escape).joined(separator: "; ") + "\n"
                }
                s += "\n"
            }
        }
        return s
    }

    // MARK: - Recommendations

    public func renderRecommendations(_ report: AuditReport) -> String {
        var s = "# Recommendations\n\n"
        s += "> Ranked cleanups for `\(report.root)`. Nothing here has been applied.\n"
        s += "> Items marked **needs sign-off** would edit or delete a real file —\n"
        s += "> check the box only after you've approved that specific change.\n\n"
        s += "Reclaimable (est.): **\(report.totalReclaimableLines) lines**. "
        s += "Top severity: **\(report.topSeverity.rawValue)**.\n\n"

        let actionable = report.recommendations.filter { $0.kind != .schemaRule }
        let schemaRules = report.recommendations.filter { $0.kind == .schemaRule }

        s += "## Cleanups\n\n"
        if actionable.isEmpty {
            s += "_None — the context surfaces look lean._\n\n"
        }
        for (i, rec) in actionable.enumerated() {
            let box = rec.requiresSignoff ? "[ ] " : ""
            s += "### \(box)\(i + 1). \(Self.escape(rec.title))\n"
            s += "- **kind:** \(rec.kind.rawValue) · **severity:** \(rec.severity.rawValue) · **risk:** \(rec.risk.rawValue) · **origin:** \(rec.origin)\n"
            if rec.estLinesSaved > 0 { s += "- **est. lines saved:** \(rec.estLinesSaved)\n" }
            if rec.estBytesSaved > 0 { s += "- **est. bytes saved:** \(Self.humanBytes(rec.estBytesSaved))\n" }
            s += "- \(Self.escape(rec.rationale))\n"
            if !rec.affectedPaths.isEmpty {
                s += "- affects:\n"
                for p in rec.affectedPaths.prefix(12) { s += "  - `\(p)`\n" }
            }
            if rec.requiresSignoff {
                s += "- ⚑ **needs sign-off** before any file is changed.\n"
            }
            s += "\n"
        }

        if !schemaRules.isEmpty {
            s += "## Schema rules (advisory — adopt to prevent re-bloat)\n\n"
            for rule in schemaRules {
                s += "- **\(Self.escape(rule.title))** — \(Self.escape(rule.rationale))\n"
            }
            s += "\n"
        }
        return s
    }

    // MARK: - Write

    public struct WrittenArtifacts: Sendable, Equatable {
        public var wikiPath: URL
        public var schemaPath: URL
        public var recommendationsPath: URL
        public var reportJSONPath: URL
    }

    /// Write all artifacts into `outDir` (created if needed). Writes ONLY here —
    /// never the source tree. Returns the paths written.
    @discardableResult
    public func writeArtifacts(_ report: AuditReport, to outDir: URL) throws -> WrittenArtifacts {
        try FileManager.default.createDirectory(at: outDir, withIntermediateDirectories: true)
        let wiki = outDir.appendingPathComponent("CONTEXT-WIKI.md")
        let schema = outDir.appendingPathComponent("CONTEXT-SCHEMA.md")
        let recs = outDir.appendingPathComponent("RECOMMENDATIONS.md")
        let json = outDir.appendingPathComponent("audit-report.json")

        try renderWiki(report).write(to: wiki, atomically: true, encoding: .utf8)
        try report.schema.write(to: schema, atomically: true, encoding: .utf8)
        try renderRecommendations(report).write(to: recs, atomically: true, encoding: .utf8)

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        try encoder.encode(report).write(to: json)

        return WrittenArtifacts(wikiPath: wiki, schemaPath: schema, recommendationsPath: recs, reportJSONPath: json)
    }

    // MARK: - Helpers

    static func humanBytes(_ bytes: Int) -> String {
        if bytes >= 1024 * 1024 { return String(format: "%.1f MB", Double(bytes) / (1024 * 1024)) }
        if bytes >= 1024 { return String(format: "%.0f KB", Double(bytes) / 1024) }
        return "\(bytes) B"
    }

    private static func iso(_ date: Date) -> String {
        let f = ISO8601DateFormatter()
        return f.string(from: date)
    }

    /// Neutralize characters that would break a markdown table cell / list line.
    private static func escape(_ s: String) -> String {
        s.replacingOccurrences(of: "|", with: "\\|").replacingOccurrences(of: "\n", with: " ")
    }
}
