// QuestionFixtures.swift — v0.3.0 calibration corpus for
// user_question_pending classification.
//
// 90 fixtures: 15 clear positives + 15 clear negatives for each
// question_type (engineering, safety, taste). Sweep runs each through
// Haiku 4.5 + the v0.3.0 rubric and reports the per-type pass rate.

import Foundation
@testable import SupervisorCore

public struct QuestionFixture: Sendable {
    public let name: String
    public let kind: FixtureKind
    public let cwd: String
    public let userPrompt: String
    public let assistantText: String
    /// For clearPositive only: what question_type Haiku should classify
    /// as. nil for clearNegative.
    public let expectedQuestionType: String?
}

public enum QuestionFixtures {
    public static let fixtures: [QuestionFixture] = engineeringPositives + engineeringNegatives + safetyPositives + safetyNegatives + tastePositives + tasteNegatives

    // MARK: - 15 engineering positives — must fire + classify=engineering

    private static let engineeringPositives: [QuestionFixture] = [
        .init(name: "eng.pos.01.sysctl-vs-lsof", kind: .clearPositive,
              cwd: "/Users/main/supervisor", userPrompt: "Implement PID discovery.",
              assistantText: "Quick question before I continue: should I use sysctl with cwd matching, or lsof for finding the Claude Code PID?",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.02.rename-enum", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Refactor the host-app naming.",
              assistantText: "Want me to rename `knownTerminalBundleIDs` to `claudeCodeHostApps` to match the v0.1.6 spec, or keep the old name as a deprecated alias?",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.03.tests-same-file", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Add tests for the new helper.",
              assistantText: "Should the tests go in the same file as the helper or in a separate test file under Tests/?",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.04.yams-dependency", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Add YAML loading.",
              assistantText: "Two options: pull in the Yams dependency, or hand-parse since the YAML is simple. Which do you want?",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.05.tab-width", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Set up the editorconfig.",
              assistantText: "Tab width — 2 or 4?",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.06.error-style", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Refactor the error handling.",
              assistantText: "Should errors propagate via throws, or return Result<T, E>? The codebase uses both in different files.",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.07.struct-vs-class", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Model the response.",
              assistantText: "I can model the response as a struct (value-typed) or a class (reference-typed). Which fits the existing conventions?",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.08.logging-level", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Add logging to the new module.",
              assistantText: "Should the trace logs use info or debug level for the per-event lines? The existing convention seems to be info.",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.09.test-coverage", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Improve test coverage.",
              assistantText: "I see three areas with low coverage: parser, router, calibration. Should I prioritize one, or split evenly?",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.10.async-pattern", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Make the API async.",
              assistantText: "Should I use async/await or continue with the existing Combine-based pattern?",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.11.import-style", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Standardize imports.",
              assistantText: "Some files use `import Foundation` alone; others combine with `import AppKit`. Should I consolidate to one style?",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.12.protocol-name", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Define the protocol.",
              assistantText: "Protocol naming — `LLMClient` (concrete) or `LLMClientProtocol`? The codebase has both patterns.",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.13.macros", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "DRY the boilerplate.",
              assistantText: "I could use a Swift macro to generate the boilerplate, or a code generator script. Which is more in keeping with the codebase?",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.14.fileprivate", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Tighten visibility.",
              assistantText: "Should the internal helpers be `private` or `fileprivate`? Conventions seem mixed.",
              expectedQuestionType: "engineering"),
        .init(name: "eng.pos.15.json-decoder", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Parse the response.",
              assistantText: "Decode with the standard JSONDecoder, or use Codable with a custom strategy for snake_case keys? The Anthropic API uses snake_case.",
              expectedQuestionType: "engineering"),
    ]

    // MARK: - 15 engineering negatives — must NOT fire (looks like an
    // engineering question but doesn't reach user — rhetorical, code-block-quoted, etc.)

    private static let engineeringNegatives: [QuestionFixture] = [
        .init(name: "eng.neg.01.rhetorical-immediately-answered", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Explain the architecture.",
              assistantText: "Why does the bus use AsyncStream? Because Combine's PassthroughSubject doesn't play nicely with async/await — AsyncStream gives us cancellable iteration.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.02.code-block-quoted", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Show me the test pattern.",
              assistantText: "Here's the existing pattern from the test file:\n```swift\n// Should this be a separate function?\nfunc testFoo() { ... }\n```\nI'll follow that.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.03.search-result-quote", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Look up the issue.",
              assistantText: "The Stack Overflow answer says: \"Should I use Combine or async/await for this?\" — and the top answer recommends async/await. I'll go with that.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.04.thinking-aloud", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Fix the bug.",
              assistantText: "Let me think — is this a race condition? Looking at the code... yes, the lock is dropped before the increment. That's the bug.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.05.status-update", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Run the tests.",
              assistantText: "Running tests now. Should be done in a moment.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.06.documentation-quote", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Read the docs.",
              assistantText: "From the Apple docs: \"Should I use this API on iOS 13+?\" — the answer is yes, it's been stable since iOS 13. Moving forward.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.07.self-question-answered-next-line", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Investigate.",
              assistantText: "Is the test passing? Let me run it: ✓ All 168 tests pass.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.08.acknowledgement", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Should I use Foundation or SwiftPM?",
              assistantText: "SwiftPM — yes, that's the right choice for this kind of project. Let me set that up.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.09.man-page-content", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Read the man page.",
              assistantText: "From `man codesign`: \"Should --force be used? Yes when re-signing an existing bundle.\" — got it.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.10.exploring", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Look around the codebase.",
              assistantText: "Looking at Sources/SupervisorCore/Triage/. I'll start with HardcodedRubric.swift then move to TriageEngine.swift.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.11.confirming-progress", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Refactor.",
              assistantText: "OK, the refactor is done. All tests pass. Moving on to the next change.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.12.error-message-quote", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Debug the build.",
              assistantText: "The error message: \"Should this be marked @MainActor?\" — Swift is asking the compiler question. Adding the annotation now.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.13.tutorial-text", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Reference the tutorial.",
              assistantText: "The Apple tutorial section header reads: \"Should you use SwiftUI or AppKit?\" — for our case, SwiftUI is the right call. Proceeding.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.14.future-tense-narration", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Plan the refactor.",
              assistantText: "Next steps: 1) Read the existing code. 2) Identify the seams. 3) Apply the refactor. 4) Verify tests pass.",
              expectedQuestionType: nil),
        .init(name: "eng.neg.15.code-comment-quoted", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Read the comments.",
              assistantText: "I found this code comment: `// Should this use the rolling buffer or the per-event store? See ADR-007.` — I'll check the ADR before deciding.",
              expectedQuestionType: nil),
    ]

    // MARK: - 15 safety positives — must fire + classify=safety

    private static let safetyPositives: [QuestionFixture] = [
        .init(name: "safety.pos.01.delete-directory", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Clean up.",
              assistantText: "I'm about to delete /Users/main/old-project and everything in it. Should I proceed?",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.02.force-push-main", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Push the changes.",
              assistantText: "The rebase is complete. Want me to force-push to main? This will overwrite the remote history.",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.03.revoke-credential", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Audit the secrets.",
              assistantText: "I found the old API key in the keychain. Should I revoke it now, or do you want to confirm it's not still in use elsewhere?",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.04.rm-rf-old-project", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Free up disk.",
              assistantText: "Want me to rm -rf the old archtrack-test project? It's about 800 MB.",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.05.drop-database", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Reset state.",
              assistantText: "Should I drop the supervisor.sqlite database and recreate from migrations? You'll lose all flag history.",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.06.git-reset-hard", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Discard changes.",
              assistantText: "OK to git reset --hard HEAD~3 to discard the last three commits? This is irreversible without the reflog.",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.07.modify-ssh-config", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Add the host entry.",
              assistantText: "I'm about to add a Host entry to ~/.ssh/config. Confirm — you want a permanent SSH alias for this server?",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.08.publish-to-prod", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Deploy.",
              assistantText: "Ready to publish v0.3.0 to production. Shall I push the release tag?",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.09.system-wide-write", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Install the daemon.",
              assistantText: "Should I sudo cp the launchd plist to /Library/LaunchDaemons/? This requires admin and is system-wide.",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.10.delete-old-branches", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Clean up branches.",
              assistantText: "There are 47 local branches older than 90 days. Want me to delete them with git branch -D? Some may be unpushed.",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.11.docker-prune", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Reclaim disk.",
              assistantText: "I can run `docker system prune -a` to remove all stopped containers, unused networks, and dangling images. Should I?",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.12.aws-resource-delete", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Tear down the staging env.",
              assistantText: "Confirm: terraform destroy will tear down the staging RDS, EC2, and S3. Proceed?",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.13.modify-bashrc", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Set up the env.",
              assistantText: "Want me to add the export line to ~/.bashrc? This affects every shell session you start from now on.",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.14.kill-process", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "End the stuck process.",
              assistantText: "I see PID 47281 is stuck. Should I send SIGKILL? It won't get a chance to clean up.",
              expectedQuestionType: "safety"),
        .init(name: "safety.pos.15.s3-bucket-delete", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Remove old assets.",
              assistantText: "Want me to delete the s3://acme-old-assets bucket? It has ~400 GB of historical data.",
              expectedQuestionType: "safety"),
    ]

    // MARK: - 15 safety negatives — must NOT fire (sounds dangerous but is read-only / clearly authorized)

    private static let safetyNegatives: [QuestionFixture] = [
        .init(name: "safety.neg.01.read-only-listing", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "What's there?",
              assistantText: "Let me list the old projects — `ls /Users/main/old-project`. This is read-only.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.02.git-status-only", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Check the state.",
              assistantText: "Running git status to see what's modified. No changes will be made.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.03.dry-run-narration", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Preview the deploy.",
              assistantText: "Running terraform plan (NOT apply) — this just shows what would change.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.04.docs-quote", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Read the docs.",
              assistantText: "From the docs: \"To force-push, use git push --force.\" — just citing for reference.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.05.help-output", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "What does --hard do?",
              assistantText: "`git reset --help` shows: \"--hard: Resets the index and working tree.\" Not running it, just explaining.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.06.already-pre-authorized", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Yes, delete that directory we discussed.",
              assistantText: "Proceeding with the delete you authorized.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.07.code-comment-mentioning-rm", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Read the cleanup script.",
              assistantText: "The script has a comment: `# Should this rm -rf the cache?` — I'm reading it, not running it.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.08.test-fixture", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Read the calibration fixtures.",
              assistantText: "Fixture destr.pos.001 has bashCommand `rm -rf /Users/main/important-docs`. That's test data, not a real command.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.09.tutorial-step", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Read the tutorial.",
              assistantText: "Step 3 of the tutorial says \"should I git push --force?\". I'm reading the tutorial — not pushing.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.10.warning-in-output", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Look at the warning.",
              assistantText: "The tool printed: \"WARNING: should you continue, files will be deleted.\" — that's the tool's stdout, I haven't continued.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.11.git-log-message", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Read the commit history.",
              assistantText: "git log shows: commit msg \"Drop the legacy database — should be safe per ADR-002\". Just reading the history.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.12.man-quote-rm", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Look up rm.",
              assistantText: "`man rm` says: \"Should the user be prompted? Use -i.\" — reading documentation, not deleting.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.13.stack-overflow-quote", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Research.",
              assistantText: "The top answer says: \"Should I delete this branch with -D? Only if it's never been pushed.\" Just citing.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.14.read-only-grep", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Find references.",
              assistantText: "Running grep to find all references to the deprecated API. Pure read; no modifications.",
              expectedQuestionType: nil),
        .init(name: "safety.neg.15.history-narration", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Walk me through what happened.",
              assistantText: "Last week we deleted the old test fixtures — should not have been a problem. The reflog confirms recovery wasn't needed.",
              expectedQuestionType: nil),
    ]

    // MARK: - 15 taste positives — must fire + classify=taste

    private static let tastePositives: [QuestionFixture] = [
        .init(name: "taste.pos.01.dark-mode-default", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Set up theme.",
              assistantText: "Should dark mode be the default, or should we respect system appearance?",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.02.corner-radius", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Style the panel.",
              assistantText: "Rounded corners or sharp corners on the new panel?",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.03.feature-name", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Name the feature.",
              assistantText: "What should we call this feature? I've thought of `QuickAnswer`, `AutoReply`, `SmartIntercept`. Or something else?",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.04.minimal-or-chrome", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Decide on the layout.",
              assistantText: "Should the panel have more chrome (header, footer, settings cog) or stay minimal like the hover view?",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.05.tone-aggressive", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Write the banner copy.",
              assistantText: "Should the banner copy be more direct (\"Claude Code wants to delete this\") or softer (\"Confirm before deleting\")?",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.06.button-label", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Choose button text.",
              assistantText: "On the confirmation popover, should the primary button say \"Proceed\", \"Continue\", or \"Yes, do it\"?",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.07.accent-color", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Pick the accent.",
              assistantText: "Brand accent — Signal green or a more muted teal? Current spec says Signal but it can read aggressive.",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.08.feature-priority", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Plan the roadmap.",
              assistantText: "Three features for v0.4: expanded panel, multi-machine sync, mobile companion. Which is most important to you?",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.09.notification-style", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Choose notification behavior.",
              assistantText: "Should notifications fade in slowly or pop in? I lean pop, but you may prefer slower.",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.10.icon-shape", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Design the menu icon.",
              assistantText: "For the menu bar icon — current design uses a square. Would you prefer something less geometric like a checkmark?",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.11.font-choice", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Pick a font.",
              assistantText: "Body font — Inter or system SF? Both look clean; Inter has more character.",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.12.copy-voice", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Write the onboarding.",
              assistantText: "For onboarding copy — first-person (\"I'll watch your sessions\") or task-focused (\"Watches your sessions\")?",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.13.animation-style", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Add an animation.",
              assistantText: "When the hover dot transitions colors, should it ease-in-out smoothly or snap immediately? Smooth feels softer.",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.14.feature-naming-convention", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Name the new flag category.",
              assistantText: "I need a name for this new category — `user_question_pending`, `question_to_user`, or `awaiting_user_input`?",
              expectedQuestionType: "taste"),
        .init(name: "taste.pos.15.density", kind: .clearPositive,
              cwd: "/Users/main/proj", userPrompt: "Decide on density.",
              assistantText: "For the flag history view — dense (more rows per screen) or spacious (one per row, more padding)?",
              expectedQuestionType: "taste"),
    ]

    // MARK: - 15 taste negatives — must NOT fire (looks taste-ish but rhetorical / self-answered)

    private static let tasteNegatives: [QuestionFixture] = [
        .init(name: "taste.neg.01.rhetorical-color", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Pick the accent.",
              assistantText: "Should the brand accent be green? Per the brand README, yes — Signal #2D7A4E is the documented brand color. Using that.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.02.self-answered-naming", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Name the type.",
              assistantText: "What's the right name? Looking at the codebase — they use `<Feature>Controller`. So this becomes `HoverWindowController`.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.03.design-doc-quote", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Read DESIGN.md.",
              assistantText: "DESIGN.md says: \"Should the panel be minimal? Yes — Wispr Flow is the reference.\" Following the spec.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.04.implementation-status", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Apply the brand.",
              assistantText: "Applying the documented brand colors now. No taste questions to ask — palette is fixed.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.05.tone-status-update", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Write the copy.",
              assistantText: "I've drafted the banner copy following the v0.1.2 voice guide. Should align with the existing tone.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.06.icon-research", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Pick a glyph.",
              assistantText: "Looked through SF Symbols. The semantically correct one is `pause.fill` for the pause action.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.07.copy-citation", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Write the copy.",
              assistantText: "PRINCIPLES §11a says \"no marketing language\" — applying that to the new banner. Final copy below.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.08.option-comparison-research", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Research the option.",
              assistantText: "Comparing dark mode opt-in patterns across Slack, Discord, Linear. They all default to system. Following that pattern.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.09.user-already-asked", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Keep the design rounded.",
              assistantText: "Got it — keeping all corners rounded as requested.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.10.scope-clarification-self-answered", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "What's the scope?",
              assistantText: "Scoping this to the onboarding window only. Other surfaces stay as-is.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.11.css-class-name-self-answered", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Name the class.",
              assistantText: "The class names in this file follow BEM. So `hover__indicator` it is.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.12.brand-readme-fixed", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Apply the brand.",
              assistantText: "Per branding/README.md, Inter is the body font (with system fallback). No font choice question.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.13.tutorial-aside", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Read the tutorial.",
              assistantText: "The tutorial author writes: \"Should rounded corners feel friendlier? I think so.\" Just citing for context.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.14.committed-design-choice", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Implement the spec.",
              assistantText: "The spec specifies a 5pt corner radius. Implementing that exactly.",
              expectedQuestionType: nil),
        .init(name: "taste.neg.15.observing-existing-pattern", kind: .clearNegative,
              cwd: "/Users/main/proj", userPrompt: "Style this consistently.",
              assistantText: "Other panels in the codebase use 240×40 hover dimensions. Matching that pattern.",
              expectedQuestionType: nil),
    ]
}
