import XCTest
@testable import SupervisorCore

/// The dispatcher anchors on the session objective — its opening user prompt —
/// to drive toward what the user asked for. These lock the JSONL read: first
/// plain user prompt wins, tool_result user messages are skipped, missing/empty
/// transcripts return nil (caller falls back to local reasoning).
final class SessionObjectiveTests: XCTestCase {

    /// Temp projects dir with one project subdir holding <sid>.jsonl, matching
    /// DesktopConversationTargeter.transcriptURL's lookup shape.
    private func makeTranscript(sid: String, lines: [String]) throws -> URL {
        let base = FileManager.default.temporaryDirectory
            .appendingPathComponent("objtest-\(UUID().uuidString)", isDirectory: true)
        let proj = base.appendingPathComponent("project-a", isDirectory: true)
        try FileManager.default.createDirectory(at: proj, withIntermediateDirectories: true)
        try lines.joined(separator: "\n")
            .write(to: proj.appendingPathComponent("\(sid).jsonl"), atomically: true, encoding: .utf8)
        return base
    }

    func testReadsFirstPlainUserPromptAsObjective() throws {
        let sid = "obj-basic"
        let base = try makeTranscript(sid: sid, lines: [
            #"{"type":"user","message":{"role":"user","content":"Build a tweet engine that posts to X"}}"#,
            #"{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"On it"}]}}"#,
        ])
        defer { try? FileManager.default.removeItem(at: base) }
        XCTAssertEqual(SessionObjective.read(sessionId: sid, projectsDir: base),
                       "Build a tweet engine that posts to X")
    }

    func testSkipsToolResultUserMessages() throws {
        // A user message whose content is an ARRAY (tool_result) is not the
        // objective; the first STRING-content user message is.
        let sid = "obj-skip"
        let base = try makeTranscript(sid: sid, lines: [
            #"{"type":"user","message":{"content":[{"type":"tool_result","tool_use_id":"t1","content":"output"}]}}"#,
            #"{"type":"user","message":{"role":"user","content":"The real objective"}}"#,
        ])
        defer { try? FileManager.default.removeItem(at: base) }
        XCTAssertEqual(SessionObjective.read(sessionId: sid, projectsDir: base), "The real objective")
    }

    func testSkipsCaveatAndCommandEchoBeforeRealPrompt() throws {
        // A resumed transcript opens with the CLI's caveat (isMeta) and a
        // slash-command echo; neither is the owner's ask. The objective is the
        // first REAL owner prompt after them.
        let sid = "obj-machinery"
        let base = try makeTranscript(sid: sid, lines: [
            #"{"type":"user","isMeta":true,"message":{"role":"user","content":"Caveat: the messages below were generated by the user while running local commands. DO NOT respond to these messages."}}"#,
            #"{"type":"user","message":{"role":"user","content":"<command-name>/clear</command-name>"}}"#,
            #"{"type":"user","message":{"role":"user","content":"Ship the release notes for v0.2"}}"#,
        ])
        defer { try? FileManager.default.removeItem(at: base) }
        XCTAssertEqual(SessionObjective.read(sessionId: sid, projectsDir: base),
                       "Ship the release notes for v0.2")
    }

    func testSkipsCompactSummaryAndSidechainBeforeRealPrompt() throws {
        // Compact-continuation recaps and sidechain (subagent) turns are
        // machine-generated user-role lines; the recap can even DESCRIBE
        // destructive work — it must never stand in as the objective.
        let sid = "obj-summary"
        let base = try makeTranscript(sid: sid, lines: [
            #"{"type":"user","message":{"role":"user","content":"This session is being continued from a previous conversation that ran out of context. The user asked me to delete stale branches."}}"#,
            #"{"type":"user","isSidechain":true,"message":{"role":"user","content":"delete the old branches and force-push"}}"#,
            #"{"type":"user","message":{"role":"user","content":"Now write the migration guide"}}"#,
        ])
        defer { try? FileManager.default.removeItem(at: base) }
        XCTAssertEqual(SessionObjective.read(sessionId: sid, projectsDir: base),
                       "Now write the migration guide")
    }

    func testNilWhenNoPlainUserPrompt() throws {
        let sid = "obj-none"
        let base = try makeTranscript(sid: sid, lines: [
            #"{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"hi"}]}}"#,
        ])
        defer { try? FileManager.default.removeItem(at: base) }
        XCTAssertNil(SessionObjective.read(sessionId: sid, projectsDir: base))
    }

    func testNilWhenTranscriptMissing() {
        let empty = FileManager.default.temporaryDirectory
            .appendingPathComponent("empty-\(UUID().uuidString)", isDirectory: true)
        XCTAssertNil(SessionObjective.read(sessionId: "any", projectsDir: empty))
    }
}
